default:
    repo_endpoint: "arytontediarjo/mpower-feature-analysis"
    git_token_path: "~/git_token.txt"
v2:
    table:
        demo:
        tap:
        walk:
        tremor:
        passive:
    feature_extraction:
        demo:
            cleaning:
                output_filename: "demographics.v2"
        tap:
            mhealthtools:
                output_filename: ""
        walk:
            pdkit:
                output_filename:
        tremor:
            mhealthtools:
                output_filename: