default:
    git:
        repo_endpoint: "arytontediarjo/mpower-feature-analysis"
        token_path: "~/git_token.txt"
    cpu:
        n_cores: 4
v2:
    table:
        demo: "syn15673379"
        tap: "syn15673381"
        walk: "syn12514611"
        tremor: "syn12977322"
        passive: "syn17022539"
    feature_extraction:
        demo:
            cleaning:
                output_filename: "demographics_v2.tsv"
        tap:
            - tool: "mhealthtools"
              output_filename: "mhealthtools_tapping_features_v2.tsv"
              columns:
                - "right_tapping.samples"
                - "left_tapping.samples"
              annotations:
                pipelineStep: "feature extraction"
                analysisType: "tapping-v2"
                task: "tapping"
              provenance:
                name: "extract tapping features using mhealthtools"
                description: "features are extracted as is"
              params:
                query_condition: "LIMIT 50"
                ts_cutoff: 30
            - tool: "mhealthtools (20 secs cutofF)"
              output_filename: "mhealthtools_20_secs_tapping_features_v2.tsv"
              columns:
                - "right_tapping.samples"
                - "left_tapping.samples"
              annotations:
                pipelineStep: "feature extraction"
                analysisType: "tapping-v2"
                task: "tapping"
                filter: "20 seconds cutoff" 
              provenance:
                name: "extract tapping features with 20 seconds cutoff"
                description: "adjusting to 20 seconds to align with V1"
              params:
                query_condition: "LIMIT 50"
                ts_cutoff: 20.5
            
        walk:
            - tool: "pdkit (7.5 seconds)"
              output_filename: "pdkit_rotation_7secs_window_walking_features_v2.tsv"
              columns:
                - "balance_motion.json"
                - "walk_motion.json"
              annotations:
                pipelineStep: "feature extraction"
                analysisType: "walking30secs-v2"
                task: "walking"
                filter: "7.5-seconds window"
              provenance:
                name: "extract walking features"
                description: "extract using 7.5 seconds window"
              params:
                query_condition: "LIMIT 50"
                window_size: 750 # sampling rate 100
            - tool: "pdkit (5 seconds)"
              output_filename: "pdkit_rotation_5secs_window_walking_features_v2.tsv"
              columns:
                - "balance_motion.json"
                - "walk_motion.json"
              annotations:
                pipelineStep: "feature extraction"
                analysisType: "walking30secs-v2"
                task: "walking"
                filter: "5-seconds window"
              provenance:
                name: "extract walking features"
                description: "extract using 5 seconds window"
              params:
                query_condition: "LIMIT 50"
                window_size: 500
        tremor:
            - mhealthtools:
                output_filename: "mhealthtools_tremor_features_v2.tsv"
                name: "extract tremor features using pdkit"
                description: "features are extracted as is"
