default:
    repo_endpoint: "arytontediarjo/mpower-feature-analysis"
    git_token_path: "~/git_token.txt"
v2:
    demo: 
        table_id: "syn15673379"
        feature_extraction:
            parent_id: "syn26601399"
            output_filename: "demographics_v2.tsv"
        baseline_superusers:
            parent_id: "syn26142249"
            output_filename: "baseline_superusers_demographics.tsv"
            provenance:
                name: "filter based on superusers"
                description: "filter demographics of superusers"
    tapping:
        table_id: "syn15673381"
        feature_extraction:
            parent_id: "syn26215075"
            output_filename: "mhealthtools_20secs_tapping_features_v2.tsv"
            provenance:
                name: "extract tapping features"
                description: "filter to 20 seconds for each reading, extract features using mhealthtools"
        clean:
            parent_id: "syn26262362"
            output_filename: "mhealthtools_20secs_tapping_features_v2_cleaned.tsv"
            provenance:
                name: "clean features"
                description: "clean features, merge with demographics"
        aggregate_users:
            parent_id: "syn26262362"
            output_filename: "mhealthtools_20secs_tapping_features_v2_agg_users.tsv"
            provenance:
                name: "aggregate tappin user-wise"
                description: "aggregate user-wise, merge demo"
        baseline_superusers: 
            parent_id: "syn26142249"
            output_filename: "baseline_superusers_tapping_features.tsv"
            provenance:
                name: "clean superusers"
                description: "filter based on superusers activity"
    tremor:
        table_id: "syn12977322"
        feature_extraction:
            parent_id: "syn26215076"
            output_filename: "mhealthtools_tremor_features_v2.tsv"
        aggregate_records:
            parent_id: "syn26341966"
            output_filename: "mhealthtools_tremor_features_v2_agg_record.tsv"
        baseline_superusers:
            parent_id: "syn26142249"
            output_filename: "baseline_superusers_tremor_features.tsv"
    walk:
        table_id: "syn12514611"
        feature_extraction:
            parent_id: "syn26215077"
            output_filename: "pdkit_rotation_walk_features_v2.tsv"
            provenance:
                name: "extract walk30secs features"
                description: "extract using PDkit Rotation Features"
        clean:
            parent_id: "syn26341967"
            output_filename: "pdkit_rotation_walk_features_v2_cleaned.tsv"
            provenance:
                name: "clean walk30 seconds data"
                description: "merged with demographics, cleaned test_user etc"
        aggregate_users:
            parent_id: "syn26341967"
            output_filename: "pdkit_rotation_walk_features_v2_agg_user.tsv"
            provenance:
                name: "aggregate walk 30 seconds user-wise"
                description: "aggregate user-wise, merge demo"
        baseline_superusers:
            parent_id: "syn26142249"
            output_filename: "baseline_superusers_walk30secs_features.tsv"
            provenance:
                name: "filter superusers"
    pd_severity:
        baseline_superusers:
            parent_id: "syn26142249"
            output_filename: "baseline_superusers_PD_conf_score.tsv"
            provenance:
                name: "predict on superusers"
                description: "user mpowerV1 data, predict on superusers"
                
