default:
    repo_endpoint: "arytontediarjo/mpower-feature-analysis"
    git_token_path: "~/git_token.txt"
v2:
    demo: 
        table_id: "syn15673379"
        feature_extraction:
            parent_id: "syn26601399"
            output_filename: "demographics_v2.tsv"
    tapping:
        table_id: "syn15673381"
        feature_extraction:
            parent_id: "syn26215075"
            output_filename: "mhealthtools_20secs_tapping_features_v2.tsv"
            provenance:
                name: "extract tapping features"
                description: "filter to 20 seconds for each reading, extract features using mhealthtools"
        aggregate_records:
            parent_id: "syn26262362"
            output_filename: "mhealthtools_20secs_tapping_features_v2_agg_record.tsv"
            provenance:
                name: "aggregate by record-level"
                description: "aggregate by record-level, merge with demographics"
        baseline_superusers: 
            parent_id: "syn26142249"
            output_filename: "baseline_superusers_tapping_features.tsv"
            provenance:
                name: "clean superusers"
                description: "filter based on superusers activity"
    tremor:
        table_id: "syn12977322"
        feature_extraction:
            parent_id: "syn26215076"
            output_filename: "mhealthtools_tremor_features_mpower_v2.tsv"
        aggregate_records:
            parent_id: "syn26341966"
            output_filename: "mhealthtools_tremor_features_v2_agg_record.tsv"
        baseline_superusers:
            parent_id: "syn26142249"
            output_filename: "baseline_superusers_tremor_features.tsv"
    walk:
        table_id: "syn12514611"
        feature_extraction:
            parent_id: "syn26215077"
            output_filename: "pdkit_rotation_walk_features_v2.tsv"
            provenance:
                name: "extract walk30secs features"
                description: "extract using PDkit Rotation Features"
        aggregate_records:
            parent_id: "syn26341967"
            output_filename: "pdkit_rotation_walk_features_v2_agg_record.tsv"
            provenance:
                name: "aggregate walk 30 seconds record-wise"
                description: "aggregate recordwise, merge demo"
        aggregate_users:
            parent_id: "syn26341967"
            output_filename: "pdkit_rotation_walk_features_v2_agg_user.tsv"
            provenance:
                name: "aggregate walk 30 seconds user-wise"
                description: "aggregate user-wise, merge demo"
        baseline_superusers:
            parent_id: "syn26142249"
            output_filename: "baseline_superusers_walk30secs_features.tsv"
            provenance:
                name: "filter superusers"
